language: python

dist: bionic

matrix:
  include:
  - python: 2.6
    dist: trusty
  - python: 2.7
  - python: 3.4
    dist: trusty
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8

install:
- pip install --upgrade pip setuptools
- pip install -r requirements-test.txt
- pip install .
- pip install coveralls

script:
- py.test -v --pep8 --cov requests_credssp --cov-report term-missing

after_success:
- coveralls
